# This file controls the settings for your Quarto template from www.marvinschmitt.com

# website settings
website:
  title: "Ashley E. Mullan"                                # Your name
  description: "Ashley E. Mullan is a Ph.D. student in the Department of Biostatistics at Vanderbilt University Medical Center. Her research interests include measurement error, missing data, and social determinants of health."   # A brief slogan (optional)
  image: img/my_image.jpg
  
  favicon: img/favicon.png
  
  # start of the navigation bar at the top of the website
  navbar:
    pinned: true
    logo: /img/logo.png
    
    # your sub-pages
    left:
      - text: "Blog"
        href: blog/index.qmd
      - text: "Software"
        href: software/index.qmd
      - text: "Talks"
        href: talks/index.qmd
      - text: "Publications"
        href: papers/index.qmd
      - text: "CV"
        href: cv/index.qmd
    
    # your social media handles
    right:
      - icon: twitter
        href: "https://twitter.com/ashley___mullan"
      - text: "{{<iconify ri:bluesky-fill>}}"
        href: "https://bsky.app/profile/ashleymullan.bsky.social"
      - icon: github
        href: "https://github.com/ashleymullan"
      - icon: linkedin
        href: "https://www.linkedin.com/in/ashley-mullan-b478b6168"
      - icon: envelope
        aria-label: email
        href: "mailto:ashley.e.mullan@vanderbilt.edu"  
  
  

# Don't touch unless you know what you are doing :) ------------
  search: 
    location: navbar
    type: textbox
  page-footer: 
    left: |
      <span class="faux-block">&#169; 2025 Ashley E. Mullan CC BY-SA 4.0</span>
    center: |
      <span class="faux-block"><a href="https://www.marvinschmitt.com/blog/website-tutorial-quarto/">View the tutorial for this template!</a></span>
    right: |
      <span class="faux-block"><a href="https://github.com/ashleymullan/ashleymullan.github.io">View source on GitHub</a></span>

project:
  type: website
  output-dir: docs

  preview: 
    port: 22222
    browser: true
    watch-inputs: true
    navigate: true

execute:
  freeze: true

format:
  html:
    fontsize: 1.1em
    theme: 
      - pulse
      - html/styles.scss
    toc: false
    code-link: true
    anchor-sections: true
    fig-cap-location: margin
    reference-location: margin
    footnotes-hover: true