---
title: "A Handy Reference"
date: "10/07/2024"
date-modified: last-modified
author: "Ashley E. Mullan"
format:
  html:
    self-contained: true
---

## An ode to being a really forgetful person

My bookmarks bar and folder of saved Tweets are graveyards full of wonderful resources that I have promised myself I'd return to at a later time and never did. Here, I've compiled and organized a list of some of these links for easy access! Out of sight, out of mind, right? 

## Links, links, and more links! 🔗

### Some Handy Definitions

1. [The Catalogue of Bias](https://catalogofbias.org/)

### For New R Converts
1. [Swirl](https://swirlstats.com/)
2. [DiscovR](https://www.discovr.rocks/discovr/)
3. [TinyStats](https://tinystats.github.io/teacups-giraffes-and-statistics/01_introToR.html)
4. [R4DS](https://r4ds.hadley.nz/)

### For Tech Enthusiasts Only
1. [Posit's Cheat Sheets](https://posit.co/resources/cheatsheets/)
2. [ScrollyTell](https://github.com/mschnetzer/scrollytell_arbeitszeit)
3. [Annotating Quarto Code](https://www.productive-r-workflow.com/quarto-tricks#code-annotation)
4. [Base R Plotting Tips](https://r-charts.com/base-r/)
5. [SQL Cheat Sheet](https://x.com/thenaijacarguy/status/1818051495553552536?s=12)
6. [Docker & Containers](https://gjhunt.github.io/repro_course/)
7. [Gorgeous R Tables](https://rfortherestofus.com/2019/11/how-to-make-beautiful-tables-in-r)

### Data, Data, and More Data
1. [General Social Survey](https://gss.norc.org/us/en/gss/get-the-data.html)
2. [Kaggle](https://www.kaggle.com/datasets)
3. [UC Irvine Repo](https://archive.ics.uci.edu/)
4. [StatSci](http://www.statsci.org/datasets.html)
5. [Data is Plural Spreadsheet (thanks to Jeremy Singer)](https://docs.google.com/spreadsheets/d/1wZhPLMCHKJvwOkP4juclhjFgqIY8fQFMemwKL2c64vk/edit?gid=0#gid=0)
6. [Rdatasets Package (thanks to Vincent Arel-Bundock)](https://vincentarelbundock.github.io/Rdatasets/index.html)
7. [DataSetsVerse Package (thanks to Andres Renzo Caceres Rossi)](https://lightbluetitan.github.io/datasetsverse/)
8. [DiversityDataKids](https://data.diversitydatakids.org/dataset?_ga=2.154954488.1380410099.1753206254-721008382.1753206254)

### Some Professional Advice and Opportunities
1. [ASA Postdoc Association](https://asapostdocs.org/)
2. [ENAR CENS (Council for Emerging and New Statisticians)](https://cens-enar.github.io/cens_website/)

### Funding Opportunities for Early Career Folks
1. [ASA Early Career Travel Fund](https://www.amstat.org/your-career/awards/student-and-early-career-travel-fund)
2. [ENAR Fostering Diversity Grant](https://www.enar.org/meetings/FosteringDiversity/)
3. [A Collection of Conference Travel Grants](https://docs.google.com/document/d/1RvWdHQL-15LJW6uYVNNQoa5bM4DenbggqEF7JIXPacI/edit?usp=sharing)


### Some Miscellaneous Items
1. [Paul's Online Math Notes: Everything You Ever Needed in Calculus](https://tutorial.math.lamar.edu/)


## Time for a plot twist 📖

I often have the same problem in movie theaters. I'll sit through a preview of an upcoming film, get excited about it, and then promptly forget about it until it pops up on my Netflix about a year and a half later. Here's a [link](https://www.ign.com/upcoming/movies) to some of the upcoming movies in the last few months of 2024!

<!--
Mathematically Uncensored Podcast: https://open.spotify.com/show/4fTwKfXkwXVk00fyZGVG5F
Interlace Journal (math and fiber arts): https://interlace-journal.org/
Kim Roth article on knitting: https://www.tandfonline.com/doi/full/10.1080/17513472.2023.2197831
Teaching Conferences: https://causeweb.org/cause/
Data Science by Design: https://datasciencebydesign.org/
Data by Design (history of viz): https://dataxdesign.io/
Wool and Water: https://www.adkwatershed.org/wool-water 
-->

